# Guia de graficación de salidas WRF

La presente es una guia de apoyo a la graficación de salidas WRF.

Dependiendo de las necesidades se pueden requerir algunas de las siguientes bibliotecas.
## Requirimientos

* netCDF4. Uso: manejo de archivos NetCDF. Instalación: conda install -c anaconda netcdf4 
* numpy. Uso: procesamiento de arreglos de datos. Instalación: conda install -c anaconda numpy 
* scipy. Uso: procesamiento adicional a numpy, en este caso extracción de datos en archivos .mat. Instalación: conda install -c anaconda scipy 
* matplotlib. Uso: graficación de datos similar a matlab. Instalación: conda install -c conda-forge matplotlib 
* cartopy. Uso: agrega funcionalidades a la graficación de matplotlib. Instalación: conda install -c conda-forge cartopy 



# Post-procesamiento de salidas WRF

### I. Lectura de archivos y procesamiento de datos
### II. Graficación
* Graficación usando pyplot y cartopy
* Otras posibilidades:
  - Graficación de mallas no estructuradas
  - Generación de contenido web

## I. Lectura de archivos NetCDF y procesamiento de datos en Python
A continuación se muestra el codigo necesario para extraer datos de archivos netCDF.
Aplica para archivos netCDF en general, no únicamente las salidas del WRF.

Hay que recordar que los archivos netCDF manejan datos en arreglos, por lo que es necesario importar las bibliotecas netCDF4 y numpy.

La biblioteca netCDF4 nos permite extraer los datos contenidos en el archivo.
Mientras que, la biblioteca numpy nos permitirá hacer operaciones optimizadas con los arreglos.

### Lectura de datos (NetCDF genérico)

En el siguiente script se utiliza la función *Dataset* para abrir el archivo de nombre *filename* y se hace referencia a él por medio de la variable (objeto) llamado *root*.

Primero importamos las bibliotecas necesarias:

In [5]:
from netCDF4 import Dataset
import numpy as np


Abrimos el archivo mediante la función *Dataset*

In [15]:
filename='wrfout_c1h_d01_1982-01-01_00:00:00.a1982'
#file opening
#with Dataset(filename,'r') as root:
root=Dataset(filename, 'r')


Se puede acceder a información del archivo, como el formato de NetCDF

In [28]:
print('Tipo de NetCDF:',root.file_format)

Tipo de NetCDF: NETCDF3_64BIT_OFFSET


o las dimensiones

In [42]:
print('Dimensiones:', root.dimensions)

Dimensiones: OrderedDict([('Time', <class 'netCDF4._netCDF4.Dimension'> (unlimited): name = 'Time', size = 24
), ('DateStrLen', <class 'netCDF4._netCDF4.Dimension'>: name = 'DateStrLen', size = 19
), ('west_east', <class 'netCDF4._netCDF4.Dimension'>: name = 'west_east', size = 617
), ('south_north', <class 'netCDF4._netCDF4.Dimension'>: name = 'south_north', size = 348
), ('bottom_top', <class 'netCDF4._netCDF4.Dimension'>: name = 'bottom_top', size = 49
)])


las dimensiones de una manera más agradable

In [45]:
for k in root.dimensions.keys():
    dim=root.dimensions[k]
    print('\t',dim.name,':',dim.size)

	 Time : 24
	 DateStrLen : 19
	 west_east : 617
	 south_north : 348
	 bottom_top : 49


También podemos acceder a los nombres de las variables por medio del método variables.keys()

In [46]:
claves=root.variables.keys()
print(claves)

odict_keys(['Times', 'P', 'Q2', 'T2', 'PSFC', 'U10', 'V10', 'XTIME', 'TSK', 'RAINC', 'RAINNC', 'SWDOWN', 'GLW', 'OLR', 'ALBEDO', 'HFX', 'QFX', 'LH', 'SST', 'SST_INPUT'])


In [51]:
T2=root.variables['T2']

Podemos acceder a la información de una variable mediante su índice

In [54]:
print(T2)

<class 'netCDF4._netCDF4.Variable'>
float32 T2(Time, south_north, west_east)
    FieldType: 104
    MemoryOrder: XY 
    description: TEMP at 2 M
    units: K
    stagger: 
    coordinates: XLONG XLAT XTIME
unlimited dimensions: Time
current shape = (24, 348, 617)
filling on, default _FillValue of 9.969209968386869e+36 used



Y a cada uno de sus atributos

In [55]:
print(T2.shape)

print(T2.units)

(24, 348, 617)
K


Y acceder a los valores mediante su clave

In [10]:
T2=np.array(root['T2'][:])
print(T2[0])
root.close()

[[299.00464 299.04724 299.08463 ... 299.09442 298.79208 298.50214]
 [299.0188  299.06006 299.0965  ... 299.28604 298.98172 298.66794]
 [299.03735 299.0755  299.10944 ... 299.48395 299.2176  298.89346]
 ...
 [288.26672 288.26282 288.25858 ... 287.7303  287.71082 287.6936 ]
 [288.21255 288.2091  288.20514 ... 287.70905 287.69705 287.6739 ]
 [288.16013 288.15723 288.15363 ... 287.68466 287.67505 287.64557]]


### Lectura de datos y procesamiento

In [9]:
from netCDF4 import Dataset
import numpy as np

filename='prom_v4.nc'
#file opening
with Dataset(filename,'r') as root:
    T2=np.array(root['T2_avg_per_m'][:])
    T2+=273.15
print(T2[0])

[[299.1014  299.10028 299.0987  ... 300.72595 300.67682 300.6267 ]
 [299.10092 299.11203 299.1098  ... 300.6539  300.68164 300.6276 ]
 [299.09998 299.11102 299.1058  ... 300.5897  300.63177 300.59756]
 ...
 [287.28778 287.2582  287.237   ... 287.9314  287.99722 288.20935]
 [287.25003 287.2218  287.20346 ... 287.89603 287.93338 288.12262]
 [287.2144  287.19485 287.17676 ... 287.9797  288.008   288.0341 ]]


## Graficación con pyplot  y cartopy (matplotlib)

## Graficación usando cartopy (features)
* Se pueden usar archivos tipo shape
* Se pueden agregar automáticamente de (descarga, descompresión, carga):
  - https://www.naturalearthdata.com/features/
  - https://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html


## Graficación de vectores

### Barbas



## Graficación de vectores en mallas no estructuradas

### Streamplot



## Graficación de vectores en mallas no estructuradas
* remallado


<br><img src=img/quiver.png width="95%" align="center" ><br>

## Graficación ejemplo:
* Imagen bitmap (png)
* Malla no estructurada
* Información de archivos .mat
* Texto, dibujos (rectángulo)


## Generación de contenido web

* Folium permite visualizar datos con leaflet



## Leaflet

<br><img src=img/leaflet.png width="95%" align="center" ><br>

## leaflet
* permite plugins (existem muchos)

https://mappinggis.com/2017/10/10-cosas-quiza-no-sabias-leaflet/