# Guia de graficación de salidas WRF

## Requirimientos

* numpy:  conda install -c anaconda numpy 
* netCDF4: conda install -c anaconda netcdf4 
* cartopy: conda install -c conda-forge cartopy 
* matplotlib: conda install -c conda-forge matplotlib 
* scipy:  conda install -c anaconda scipy 



# Post-procesamiento de salidas WRF

### I. Lectura de archivos y procesamiento de datos
### II. Graficación
* Graficación usando pyplot y cartopy
* Otras posibilidades:
  - Graficación de mallas no estructuradas
  - Generación de contenido web

## I. Lectura de archivos NetCDF y procesamiento de datos en python

### Lectura de datos (NetCDF genérico)

In [8]:
from netCDF4 import Dataset
import numpy as np

filename='prom_v4.nc'
#file opening
with Dataset(filename,'r') as root:
    T2=np.array(root['T2_avg_per_m'][:])
print(T2[0])

[[25.95143   25.950289  25.9487    ... 27.575968  27.526814  27.476727 ]
 [25.95092   25.96205   25.959808  ... 27.503893  27.531649  27.4776   ]
 [25.949978  25.961044  25.95581   ... 27.439697  27.481775  27.447577 ]
 ...
 [14.1377945 14.10822   14.0870075 ... 14.781396  14.84724   15.059344 ]
 [14.100042  14.071801  14.053479  ... 14.74602   14.783372  14.972626 ]
 [14.064387  14.044859  14.026752  ... 14.829721  14.858014  14.884087 ]]


### Lectura de datos y procesamiento

In [9]:
from netCDF4 import Dataset
import numpy as np

filename='prom_v4.nc'
#file opening
with Dataset(filename,'r') as root:
    T2=np.array(root['T2_avg_per_m'][:])
    T2+=273.15
print(T2[0])

[[299.1014  299.10028 299.0987  ... 300.72595 300.67682 300.6267 ]
 [299.10092 299.11203 299.1098  ... 300.6539  300.68164 300.6276 ]
 [299.09998 299.11102 299.1058  ... 300.5897  300.63177 300.59756]
 ...
 [287.28778 287.2582  287.237   ... 287.9314  287.99722 288.20935]
 [287.25003 287.2218  287.20346 ... 287.89603 287.93338 288.12262]
 [287.2144  287.19485 287.17676 ... 287.9797  288.008   288.0341 ]]


## Graficación con pyplot  y cartopy (matplotlib)

## Graficación usando cartopy (features)
* Se pueden usar archivos tipo shape
* Se pueden agregar automáticamente de (descarga, descompresión, carga):
  - https://www.naturalearthdata.com/features/
  - https://www.ngdc.noaa.gov/mgg/shorelines/gshhs.html


## Graficación de vectores

### Barbas



## Graficación de vectores en mallas no estructuradas

### Streamplot



## Graficación de vectores en mallas no estructuradas
* remallado


<br><img src=img/quiver.png width="95%" align="center" ><br>

## Graficación ejemplo:
* Imagen bitmap (png)
* Malla no estructurada
* Información de archivos .mat
* Texto, dibujos (rectángulo)


## Generación de contenido web

* Folium permite visualizar datos con leaflet



## Leaflet

<br><img src=img/leaflet.png width="95%" align="center" ><br>

## leaflet
* permite plugins (existem muchos)

https://mappinggis.com/2017/10/10-cosas-quiza-no-sabias-leaflet/